image:
  file: .gitpod.Dockerfile
tasks:
  - name: Build complete version of snake-fury
    before: git checkout complete-solution
    init: stack build
    command: stack install
vscode:
  extensions:
    - haskell.haskell